### ISSUE TITLE
Remove the enum value HANDLED from ExtensionResultStatusType

### ISSUE THREAD

**Issue by ktisdell** [BroadleafCommerce/BroadleafCommerce#1089]
The ExtensionManager is responsible for taking hints and determining whether to continue or stop on the return of an extension handler.  The problem is that right now, we have HANDLED, HANDLED_CONTINUE, and HANDLED_STOP.  HANDLED makes things ambiguous to an implementor of the extension hander.  We should only allow HANDLED_CONTINUE and HANDLED_STOP to make it clear to the implementor of the extension handler what they are trying to do.  It can still be left up to the extension manager to ignore the hint and either continue or stop as necessary.

**Comment by phillipuniverse** [comment]
FYI I am undeprecating this but enhancing the docs around it. The reason is because `HANDLED` actually makes sense when you are returning the result of the `ExtensionManager`. The only time it doesn't make much sense is when you are returning results from `ExtensionHandlers` inside of the `ExtensionManager`.
