### ISSUE TITLE
Forget password is not working

### ISSUE THREAD

**Issue by decpradeep** [BroadleafCommerce/BroadleafCommerce#1104]
Hi All, I have configured broadleaf-framework 3.0.2-GA in my system but i could see forget password is not working i can't able to figure out where the problem relies. is that a version based issue or should i do something else to make it work? i have referred broadleaf commerce documentation to configure in my system.

**Comment by songdragon** [comment]
Reset password in demo site doesn't work correctly after I reset password via email. After I reset password, I could not login. The reason is that resetPasswordUsingToken() in CustomerServiceImpl
```
 if (! response.getHasErrors()) {
            customer.setUnencodedPassword(password);
            saveCustomer(customer);
            fpst.setTokenUsedFlag(true);
            customerForgotPasswordSecurityTokenDao.saveToken(fpst);
        }
``` 
doesn't set passwordChangeRequired to false. This will result in login fail because following code check this field in class AbstractUserDetailsAuthenticationProvider.
```
 if (!user.isCredentialsNonExpired()) {
                logger.debug("User account credentials have expired");
```

  
Could you check this issus has been fixed in new version? Thank you!
