### ISSUE TITLE
Order Search in Admin fails for IE 8

### ISSUE THREAD

**Issue by vivekjuneja** [BroadleafCommerce/BroadleafCommerce#1219]
Found issue while searching for Orders in IE 8. 

The following code in `listGrid-filter.js` under `broadleaf-open-admin-platform`  does not extract the value in the Search form field : 

```javascript
var search = $(this).closest('form').find('input').val();
```

This leads to the issue where clicking on Search button under Orders in Admin does not work in IE 8.

**Comment by ktisdell** [comment]
@brundonsmith can you please take a look at this in 3.1.x and make it a priority?

**Comment by brundonsmith** [comment]
After just trying this out, $(this).closest('form').find('input').val() seems to return the correct value in IE8. However, you are correct that Order search doesn't work on IE8. I'll continue to investigate.

**Comment by brundonsmith** [comment]
This was quite the rabbit hole. I spent a long time chasing down DOM manipulation incompatibilities with IE8, eventually finding out that the manipulation code wasn't being consistently called because redactor.js doesn't work with IE8, and calling its function was throwing a 'function undefined' error which was stopping execution of the script.
