### ISSUE TITLE
There is no way to clear out a primary image for a product

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1228]
If you add a 'Primary Image' to a Product, there is no way to remove that image. You can change it to something else but you cannot actually set it to blank.

This will require modifications to the `MediaFieldPersistenceProvider` to manipulate the defaultSku media map with null values passed in.

**Comment by cja769** [comment]
By setting the value of the image to the empty string then it works. Setting it to null does cause problems, but setting the value to the same thing that it's set to when a new Product is added is the solution. This is just needs a remove button added next to the add button to clear the image value so that it's the empty string.

**Comment by phillipuniverse** [comment]
Some additional conversation went on here and I wanted to capture that.

The above suggestion doesn't work because all that does is set the `url` property to an empty string. What should happen is that the `primary` key from the map should be removed and the `Media` instance also removed.

When an image is associated in this fashion as the primary image, 2 records get written:

```sql
INSERT INTO BLC_SKU_MEDIA_MAP (MAP_KEY, MEDIA_ID, BLC_SKU_SKU_ID) VALUES ('primary', 10, 20);
INSERT INTO BLC_MEDIA (MEDIA_ID, URL) VALUES (10, '/path/to/image.png');
```

Both of these entries need to be deleted.

**Comment by cja769** [comment]
After updating the populateValue method in MediaFieldPersistenceProvider so that instance.defaultSku.skuMedia map is updated so that the "primary" entry is deleted. This worked for DemoSite but does not in DemoSitePrivate. I think that it's having an issue dealing with DemoSitePrivate's sandboxing. I also think to deal with this problem it will have something to do with the extension handler.

**Comment by phillipuniverse** [comment]
@cja769 can you add some more specific information like what happens in the database and the code that you have written that isn't doing what you expect?

**Comment by cja769** [comment]
```populateValueRequest.getFieldManager().setFieldValue(instance,                       populateValueRequest.getProperty().getName(), null);``` should be deleting the key and value in the map for when the key is "primary", which should delete the relationship in the database but it doesn't for DemoSitePrivate. When removing the primary media from a product in DemoSite, the database reflects the change by removing the entry in blc_sku_media_map mapping the media entity to the sku entity. On the other hand, when removing the primary media from a product in DemoSitePrivate, the database does not add a sandbox entry nor anything else. The database is unchanged. When the media is simply changed to a different kind of media then a sandbox entry is added in blc_sku_media_map and in blc_media.
