### ISSUE TITLE
When adding a product to a category, if you click the product multiple times, you end up with multiple add operations on the server

### ISSUE THREAD

**Issue by jefffischer** [BroadleafCommerce/BroadleafCommerce#1250]
The system currently does not protect well against accidental, multiple user clicks on a row in the list grid. This goes for any adorned target list grid that is select only without any additional maintained fields.

**Comment by lakshmikalyani** [comment]
@jefffischer..Hi this issue is not only observed with AdornedTargetCollection but the same with other collection fields also. I tried mapping permissions to a user by clicking on a permission multiple times and can see multiple requests being sent to the server.The same with Roles as well.
The fix mentioned above is not working for other collection fields.

**Comment by phillipuniverse** [comment]
@lakshmikalyani as this issue and subsequent commits are already apart of a release, please open a new issue describing the problem and what versions are affected.
