### ISSUE TITLE
Search facets not being displayed in desired order

### ISSUE THREAD

**Issue by alex0791** [BroadleafCommerce/BroadleafCommerce#1272]
**Broadleaf Framework** : 3.1.8-GA
**Admin demo project** : 3.1.8-GA

**Steps to reproduce**

1.) Go to admin
2.) Add a search facet ``S1``(display order 1) on the parent category ``P``
3.) Add the same search facet ``S1``(display order 1) and another search facet ``S2``(display order 2) on another child category ``C`` with parent category ``P``
4.) Go to the site to category ``C``

**Expected result** :  Search facet ``S1`` and ``S2`` should appear as search facets exactly in this order (``S1``, ``S2``)
**Actual result** :  The search facets appear ``S2`` and ``S1``. The facets defined in the parent ``P`` categories always appear at the bottom.

**Note** In the ``org.broadleafcommerce.core.catalog.domain.CategoryImpl#getCumulativeSearchFacets`` there is a filtering of facets done, but the ``!returnFacets.contains(csf.getSearchFacet())`` condition is never checked given the fact that the argument is a ``org.broadleafcommerce.core.search.domain.SearchFacet`` and the list contains ``org.broadleafcommerce.core.search.domain.CategorySearchFacet`` entities

**Comment by phillipuniverse** [comment]
Thanks for bringing this to our attention. Just FYI, the patch that this will go in is 3.1.13-GA. It should be a straightforward upgrade from 3.1.8-GA that you are currently targeting, see [the release notes](http://www.broadleafcommerce.com/docs/core/current/release-notes/3.1.12-ga). You can see earlier release notes from the lefthand nav.

**Comment by phillipuniverse** [comment]
What I found was that if I did as you said, then I actually got duplicate facets which is a bug. If I add a "Manufacturer" facet to a parent category and then add that same "Manufacturer" facet to a child category, when I build the cumulative list of facets for the category I should exclude those from the parents. As you deduced, this was a bug because of the incorrect comparison.

However, I don't agree with the ordering assessment. The display of CategorySearchFacets are controlled by the `sequence` property of CategorySearchFacet. To me, this means that the ordering should only apply to other search facets related to that specific category and does not speak to ordering of facets within other categories. I can obviously see it the other way too; that you should intersperse parent category facet ordering within child category facet ordering.

That said, this is not a change I want to make as a patch release of 3.1 and instead will leave it for you to customize. The easy customization point would be to subclass and override `SolrSearchServiceImpl.getCategoryFacets()` and do whatever sorting you want from there.

Thanks for the report, the facet duplication has been resolved with the above commit.

**Comment by Pr0TuX** [comment]
Here is another strange/funny related bug/usability issue, if you reorder categories search facets and than you press save button, then reordering is lost..
