### ISSUE TITLE
Broadleaf commerce 3.0.2 GA - Controlling Admin Section Values

### ISSUE THREAD

**Issue by decpradeep** [BroadleafCommerce/BroadleafCommerce#1286]
We are using Broadleaf commerce 3.0.2 GA. We are trying to control Left Hand Menu in an admin section for one of the Admin user for the custom controller file. We are expecting to Hide the Particular Menu / Sub Menu for that User, but we are unable to do it. We are following BLC_ADMIN_SECTION, BLC_ADMIN_MODULE, BLC_ADMIN_SEC_PERM_XREF tables to insert those particular Menus. Please guide us how to do it.

We have followed this documentation to create the custom controller - http://www.broadleafcommerce.com/docs/c ... ontrollers

And another issue is we have created a new custom admin module. Below that custom admin module we have created a admin section value. Once we click the admin section value page the admin module Menu collapse automatically. But in the default broadleaf commerce it doesn't collapse automatically EX: Category Menu. Kindly advise how to control the same?

**Comment by phillipuniverse** [comment]
@decpradeep make sure that the the user has **no** permissions (either directly related or indirectly related via the user roles) that are also in `BLC_ADMIN_SEC_PERM_XREF`.

As for hiding the correct menu items, that menu is built via [leftNav.html](https://github.com/BroadleafCommerce/BroadleafCommerce/blob/b457d5f2c5649d8a2ce839e70847199bad0ea4ab/admin/broadleaf-open-admin-platform/src/main/resources/open_admin_style/templates/layout/partials/leftNav.html). This assumes there is a model object for `currentAdminSection` and `currentAdminModule`. `AdminAbstractController` (which your controller can/should extend from if not `AdminBasicEntityController`) contains a `setModelAttributes` method that looks like this:

```java
protected void setModelAttributes(Model model, String sectionKey) {
    AdminSection section = adminNavigationService.findAdminSectionByURI("/" + sectionKey);

    if (section != null) {
        model.addAttribute("sectionKey", sectionKey);
        model.addAttribute(CURRENT_ADMIN_MODULE_ATTRIBUTE_NAME, section.getModule());
        model.addAttribute(CURRENT_ADMIN_SECTION_ATTRIBUTE_NAME, section);
    }
    
    extensionManager.getProxy().setAdditionalModelAttributes(model, sectionKey);
}
```

It looks up the section by URL and sets it on the model so that the menu is displayed correctly. You would need to do the same in your controller to achieve that functionality as well.

You are also on a very old version of 3.0. The latest version is 3.0.15-GA. You can see release notes for upgrading the 3.0 line at http://www.broadleafcommerce.com/docs/core/current/release-notes/3.0.15-ga. If there was a bug here we would not patch the 3.0.2 version it would go in 3.0.15-GA.

Future questions like this should be on the forums at http://forum.broadleafcommerce.org.

**Comment by decpradeep** [comment]
@phillipuniverse Thanks for replying my post. 

Entry has to be there in BLC_ADMIN_SEC_PERM_XREF but I would like to hide it for certain user and make it visible for some user. 

menu items issue has been resolved. Thanks for that. 

We will update to the latest version soon.
