### ISSUE TITLE
ToOne relationships that are marked as FetchType.LAZY cannot be cast to their subtypes without a manual refresh

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1310]
Let's say we have this example:

```
public class MySku extends SkuImpl
    @Column("NEW_PROPERTY")
     public String myProperty;
     ...

    public String getMyProperty() {
        return myProperty;
    }
}
```

Then ensure that you create a `MySku` instance in the database and then add that to your cart. In order to get around the problem of a ton of joins with catalog and order extensions (see #1209), we have changed the relationship from `DiscreteOrderItem` to `Sku` to be `FetchType.LAZY`:

```
@ManyToOne(fetch = FetchType.LAZY, targetEntity = SkuImpl.class, optional=false)
@JoinColumn(name = "SKU_ID", nullable = false)
@Index(name="DISCRETE_SKU_INDEX", columnNames={"SKU_ID"})
@AdminPresentation(friendlyName = "DiscreteOrderItemImpl_Sku", order=Presentation.FieldOrder.SKU,
        group = OrderItemImpl.Presentation.Group.Name.Catalog, groupOrder = OrderItemImpl.Presentation.Group.Order.Catalog)
@AdminPresentationToOneLookup()
protected Sku sku;
```

So, when you call `discreteOrderItem.getSku()`, the instance that you actually get back is a javaassist object (aka a Hibernate proxy) that conforms to SkuImpl (it just looks at the `@ManyToOne` information to determine this). Thus, this invocation will fail with a class cast exception:

```
// Throws ClassCastException
String myProperty = ((MySku) discreteOrderItem.getSku()).getMyProperty();
```

Casting the `getSku()` call to a `Sku` or `SkuImpl` will always succeed.

Here's where it gets fun. Because it's loaded lazily, when you try to actually get a property from the Sku it goes and looks it up (db or cache) and then gives you the right type. Thus, if you do this then it will succeed:

```
// force a load of the Sku
discreteOrderItem.getSku().getId();
String myProperty = ((MySku) discreteOrderItem.getSku()).getMyProperty();
// all good
```

The above is a workaround. What we should do in the framework is in the getter, go ahead and refresh the Sku instance. According to the almight internet at http://stackoverflow.com/questions/17155452/hibernate-lazy-loading-for-reverse-one-to-one-workaround-how-does-this-work, it looks like the addition of `@LazyToOne(LazyToOneOption.NO_PROXY)` to that property should work because then whenever the reference is accessed the instance will be refreshed automatically.

The DiscreteOrderItem -> Sku relationship is 1 instance but I'm sure there are others. Doing a quick search in my projects:

- BundleOrderItem - sku and product
- DiscreteOrderItem - sku and product
- OrderItem - category and giftWrapOrderItem

Credit to @pbaggett for going through the debugging to figure this out.

@jefffischer you might have an opinion here.

**Comment by jefffischer** [comment]
If MySku extends Sku, then (MySku) discreteOrderItem.getSku() would work, correct?

**Comment by bpolster** [comment]
We don't have this in too many places.   An acceptable work around might be ...

```
Sku getSku() {
     // Code added so that casts to subclasses work even though this is a hibernate proxy object.
     if (sku != null) {
            sku.getId();
     }
     return sku;
}
```

**Comment by phillipuniverse** [comment]
@jeffischer theoretically with the addition of that annotation that will be the case. Currently it's not.

@brianp that will only be required if the annotation doesn't work

**Comment by pbaggett** [comment]
In an effort to get `@LazyToOne(LazyToOneOption.NO_PROXY)` working for us I attempted to use the hibernate build-time bytecode enhancement but ran into the following exception on many fields during build:
```
[ERROR] Unable to enhance class [org.broadleafcommerce.core.rating.domain.ReviewDetailImpl]
org.hibernate.bytecode.enhance.spi.EnhancementException: Unable to enhance persistent attribute [org.broadleafcommerce.core.rating.domain.ReviewDetailImpl:customer]
	at org.hibernate.bytecode.enhance.internal.PersistentAttributesEnhancer.enhancePersistentAttribute(PersistentAttributesEnhancer.java:104)
	at org.hibernate.bytecode.enhance.internal.PersistentAttributesEnhancer.enhance(PersistentAttributesEnhancer.java:69)
	at org.hibernate.bytecode.enhance.internal.EntityEnhancer.enhance(EntityEnhancer.java:71)
	at org.hibernate.bytecode.enhance.spi.Enhancer.enhance(Enhancer.java:161)
	at org.hibernate.bytecode.enhance.spi.Enhancer.enhance(Enhancer.java:107)
	at org.hibernate.bytecode.enhance.plugins.MavenEnhancePlugin.processEntityClassFile(MavenEnhancePlugin.java:150)
.......
Caused by: javassist.NotFoundException: org.broadleafcommerce.profile.core.domain.Customer
	at javassist.ClassPool.get(ClassPool.java:450)
	at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:592)
	at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:542)
	at javassist.CtField.getType(CtField.java:371)
	at org.hibernate.bytecode.enhance.internal.AttributeTypeDescriptor.resolve(AttributeTypeDescriptor.java:102)
```
I then tried activating the hibernate runtime bytecode weaver by adding `<property name="hibernate.ejb.use_class_enhancer" value="true"/>` to persistence-common.xml which resulted in the following exception frequently, and the `@LazyToOne(LazyToOneOption.NO_PROXY)` still had no effect:
```
[artifact:mvn] [ WARN] 16:29:41 ClassFileTransformerAdapter - Error weaving class [null] with transformer of class [org.hibernate.ejb.instrument.InterceptFieldClassFileTransformer]
[artifact:mvn] java.lang.instrument.IllegalClassFormatException
[artifact:mvn] 	at org.hibernate.ejb.instrument.InterceptFieldClassFileTransformer.transform(InterceptFieldClassFileTransformer.java:79)
[artifact:mvn] 	at org.springframework.orm.jpa.persistenceunit.ClassFileTransformerAdapter.transform(ClassFileTransformerAdapter.java:56)
[artifact:mvn] 	at org.springframework.instrument.classloading.InstrumentationLoadTimeWeaver$FilteringClassFileTransformer.transform(InstrumentationLoadTimeWeaver.java:184)
[artifact:mvn] 	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[artifact:mvn] 	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
......
```
This is caused by lambda expressions in java 8 because they have no class name, there is a bug open for this currently: https://hibernate.atlassian.net/browse/HHH-9541

I will now simply add a `deproxy()` method that can be called where we use lazy loading to receive the actual concrete instance.

**Comment by jefffischer** [comment]
This impacts the admin as well. The use case where this shows up is when viewing an order in the admin. The DiscreteOrderItem has a sku reference that is a proxy, which can confuse the admin when retrieving the order, resulting in a NullPointerException. The fix is to enhance FieldManager with deproxy behavior.

**Comment by SpOOnman** [comment]
There is also a side effect with a proxy object. If an entity manager reads an object and creates a proxy of a main class and during the same transaction this object is used in other association, without getting called with getter (and unproxying) - proxy still remains as an instance of main class that cannot be casted to subclass. This can have side effects all over a system and it's hard to spot.

I've ended up changing annotation on BundleOrderItem's product with targetEntity=MyProductImpl so that correct proxy is being created.
