### ISSUE TITLE
BasicPersistenceModule.cleanupFailedPersistenceAttempt wrongly throws NoSuchFieldException

### ISSUE THREAD

**Issue by smmckay** [BroadleafCommerce/BroadleafCommerce#1324]
On entity add, persisting properties that refer to the parent will cause the parent to be persisted. The parent may fail persistence--NOT NULL foreign key field is null, bean validation failure, etc. Then `cleanupFailedPersistenceAttempt` will try to obtain the parent entity's `id` field. If the parent entity is subclassed this will fail, because `Class.getDeclaredField` doesn't check superclasses.

What's bringing this to light is the new MediaXref scheme. As a result, it seems like entities with Media fields are going to have a very hard time giving proper validation errors unless all validation is removed from Hibernate and the DB schema, and that's not something I'm willing to do.

**Comment by pbaggett** [comment]
Hey @smmckay thanks for reporting this issue. I believe I have a fix but it would be great if you could supply your particular subclass so I can ensure it will be fixed as well.

**Comment by smmckay** [comment]
I don't think I can, due to NDA. A Product subclass with an instance containing a valid MediaXref and one or more invalid fields would illustrate my problem--the Product subclass would have to fail persistence at the Hibernate level, due to schema violation or some such.

**Comment by pbaggett** [comment]
@smmckay We've fixed the originally reported bug along with an additional bug found when updating an entity under similar conditions.

In both cases, what is happening is that the `MediaFieldPersistenceProvider` (and `RuleFieldPersistenceProvider` in other cases) is performing a persist/merge on entities that haven't been fully validated yet, this is handled in the `BasicPersistenceModule` however there was an issue with cleaning up a subclassed entity as originally reported and also when updating an entity a `ValidationException` wasn't being caught and handled similarly when an entity failed Hibernate validation during the early persist/merge.

The `BasicPersistenceModule` handles failures during the early persist/merge by tracking the exception and continuing on to final validation. This final validation will find and mark validation errors that will be presented to the user and subsequently changes will not be persisted if there is an error. If for some reason final validation didn't find the error(s) that caused hibernate validation to fail (say due to a misconfiguration like a missing `@Valid` on a related entity when using JSR303) then the exception will be re-thrown so that changes will not be persisted.
