### ISSUE TITLE
Empty Featured Products on CMS Pages

### ISSUE THREAD

**Issue by arunmrao** [BroadleafCommerce/BroadleafCommerce#1332]
Using 4.0.0-RC1 - In DemoSite/site, when I click on the last 2 tabs - "New to Hot Sauce" and "FAQ", I see the Featured Products box with nothing in it (on the right site)

**Comment by ncrum** [comment]
Going to look into this, but I believe this is because those are example content-managed pages, without any content to them. Looking at the `Hot Sauces` page you can see Featured Products is populated, because it has content provided. 

I believe this is intended to be this way.
@phillipuniverse or @bpolster could you confirm this?

**Comment by phillipuniverse** [comment]
@arunmrao this is pretty easy to change by editing `default.html` in the demo site. This is currently hardcoded to category 2001 (line 18):

```html
<blc:related_products categoryId="2001" quantity="3"/>  
```

But you can change it to whatever you want like 2002 which does have featured products:

```html
<blc:related_products categoryId="2002" quantity="3"/>  
```

Or just remove it entirely.
