### ISSUE TITLE
NPE on password reset

### ISSUE THREAD

**Issue by regcole** [BroadleafCommerce/BroadleafCommerce#1359]
NPE when using deprecated flow of checkPasswordResetToken method in CustomerServiceImpl.  
The old version of method did not require a `Customer` so when the deprecated method is called; NPE will result around line 581 where it has the following block 
``` java
 CustomerForgotPasswordSecurityToken fpst = null;
        if (!response.getHasErrors()) {
            List<CustomerForgotPasswordSecurityToken> fpstoks = customerForgotPasswordSecurityTokenDao.readUnusedTokensByCustomerId(customer.getId());

```

Method should be changed to account for when `Customer` is null, use the `Customer` from the `CustomerForgotPasswordSecurityToken`

**Comment by pbaggett** [comment]
If you implement the deprecated version of `PasswordEncoder` (`org.springframework.security.authentication.encoding.PasswordEncoder`) using a self-salting algorithm such as bcrypt a valid `Customer` object is required during the reset password operation, therefore you cannot call `CustomerServiceImpl.checkPasswordResetToken(String)` or pass a `null` `Customer` to `CustomerServiceImpl.checkPasswordResetToken(String, Customer)` in custom code.

This is because legacy token lookup is implemented by hashing the supplied token and salt and pulling the token directly from the database. When using a self-salting algorithm, the salt is randomly generated during the `encode` operation and thus whenever comparing against this encoded hash, you must use the `matches` operation going forward for comparison; calling `encode` again using the same input values will result in a different encoded hash.
