### ISSUE TITLE
AdminUX - ListGrid single/multi select & submit for modals

### ISSUE THREAD

**Issue by ckittrell** [BroadleafCommerce/BroadleafCommerce#1396]
https://github.com/BroadleafCommerce/QA/issues/648

**Comment by Stefano-Messi** [comment]
Hi,
any news about this issue?
multi select doesn't work

thanks

**Comment by ckittrell** [comment]
@Stefano-Messi These changes have been in the codebase since our `5.0.0-GA` release. Can you explain the specific use case that you are trying to implement?

**Comment by Stefano-Messi** [comment]
I would like to set multiple selection for sku, for example in product bundles or other custom objects (in my case there is no need to set a quantity or price).

I tried using the FormBuilderExtensionHandlerImpl setting the multi select type:

listGrid.setSelectType (ListGrid.SelectType.MULTI_SELECT);
listGrid.setModalRowActions (Arrays.asList (DefaultListGridActions.MULTI_SELECT));
listGrid.setAddMethodType (AddMethodType.SELECTIZE_LOOKUP);

but the modal button in adminUX has no associated event.

looking in the file listGrid.js I noticed that only the single selection is handled:

$ ('body'). ('click', 'button.list-grid-single-select', function () {...}

I can't find multiple selection:
// missing in listGrid.js
$ ('body'). ('click', 'button.list-grid-multi-select', function () {...}


Thanks in advance

**Comment by Jerry77oz** [comment]
HI @Stefano-Messi, the multi-select functionality was put in specifically for an enterprise module called **Enterprise** (Workflow and Approvals). While the code was put in place in order to be able to enhance upon it down the line, currently there is no immediate plan to do so in any other place.

What you are referring to is indeed a custom scenario like you point out. Broadleaf is extensible enough to allow you to extend/customize as you need. In this case, it sounds like you would need to add your custom JS to handle your use case. In addition, you would want to extend (possibly override if you want to replace logic) the Admin Controllers that handle the requests when adding skus to do what you need.

In case you haven't already, you can find more information in the following documentation which relates to what you would need.

https://www.broadleafcommerce.com/docs/core/current/tutorials/admin-customization-tutorials/adding-javascript

https://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/admin/admin-controllers

Hope this helps!
Jerry

**Comment by Stefano-Messi** [comment]
Hi @Jerry77oz 

thanks for the links, I had already started customizing javascript and controller, I was hoping to find this feature already implemented in the community version :)

regards
