### ISSUE TITLE
Allow billing and shipping information to be populated from the order on payment types other than credit card

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/BroadleafCommerce#1423]
Currently only credit card payments have the ability to glean things like shipping information, billing information, customer information, etc. This restriction is unnecessary and some third party hosted payments need this information to function properly.

**Comment by ktisdell** [comment]
The fix for this is causing issues in the refund flow.  The method `translatePaymentTransaction` invokes `populateTotals` and `populateDefaultLineItemsAndSubtotal `.  These reset the total to ZERO when a refund is being done, which is incorrect.  One thought is to use an if statement to call those methods only if the transaction type is a auth, capture, or auth and capture. @elbertbautista

**Comment by Jerry77oz** [comment]
Closing this issue and tracking the problem with **Refunds** in #1449
