### ISSUE TITLE
Page field translations via admin ui persist with wrong entity type

### ISSUE THREAD

**Issue by tonyharrison** [BroadleafCommerce/BroadleafCommerce#1581]
BLC Version - 5.0.x / 5.1.x
When adding translations for a CMS page through the Admin UI translation is persisted with entity type PageTemplate, rather than entity type Page..

This also prevents translations inserted through SQL (such as page translations in demo site) from showing up in the list of translations for a given field.

**Comment by phillipuniverse** [comment]
Also reported [on Gitter](https://gitter.im/BroadleafCommerce/BroadleafCommerce?at=59e60a3fd6c36fca31617f94) that this is happening in the latest 5.2.2-GA

**Comment by oleksiimiroshnyk** [comment]
@tonyharrison @phillipuniverse what is CMS page in demosite private 5.1 ?
Can you prodive more descriptive steps to reproduce please ?

**Comment by phillipuniverse** [comment]
@oleksiimiroshnyk did you verify on the frontend when you changed the locale through the link on the banner in the UI?

**Comment by tonyharrison** [comment]
@oleksiimiroshnyk 
To reproduce. 
(I just checked against 5.2.2-GA tag of DemoSite repo)

### In Admin
1. Go to Content -> Pages
2. 2. Select Page (eg: About Us)
3. 3. Click on Translation Link for field (eg: Body)
4. 4. Add Translation for a locale (eg: French (France))

### In Demo Site
1. Go to about us page
2. Change Language/Locale to French (France) in the top banner/header or add `?blLocaleCode=fr_FR` to url.
3. The page will still show the default 'test content' under the 'About Us' header instead of your translation.

### In DB
Look at BLC_TRANSLATION table, you will see the new entry you added has been saved with ENTITY_TYPE of PageTemplate. 

The SiteApp looks for translations for the 'About Us' Page, ie:  ENTITY_TYPE of Page, ENTITY_ID of 1, which logically is correct in my opinion. The AdminApp however treats translations as data  belonging to a PageTemplate, which is not really correct, the translation belongs to the page, not the template.

### Additional
The SQL scripts for the demo site insert into BLC_TRANSLATIONS a spanish translation (es) for each of the three pages in the demo site with ENTITY_TYPE of Page. So if you look at the demo site and change language/local to Spanish (Spain) you will see the translation,  however because this mismatch between SiteApp and AdminApp, if you go into Admin, and click Translation on the body field of any of the pages you will not see the translations inserted by the demo site SQL.

**Comment by oleksiimiroshnyk** [comment]
@phillipuniverse nope I didn't, but checked it is not not showing expected translation...

@tonyharrison I can't reproduct the issue in part of saving - it saves correctly with Entity type = Page, on version 5.1 & 5.2
The issue with translations added on startup is that they have "wrong" site_disc column value.  SiteFilterEnabler class adds constraints for sites ids. And in this case it checks if site_disc value is in [-2,-3] range, while in DB we have -1....

The problem with translations added via admin and not applying on site is a different story. I'm still investigating it, but looks like filters applied to the query results in that we fetch "archived" records.
I'm not sure why do we save translations in that  way - maybe the issue is there... or the issue in filters, or the logic how we deal with query result

@phillipuniverse can you please take a quick look if translations saved in DB as expected ? - just add some translation and check blc_translation table.

**Comment by tonyharrison** [comment]
@oleksiimiroshnyk
 It sounds like you might be using enterprise modules, yes? I am only checking 'community edition'.

**Comment by oleksiimiroshnyk** [comment]
yep, I use DemoSitePirvate for 5.1 ReferenceSite for 5.2 ..

**Comment by oleksiimiroshnyk** [comment]
Ok, translations are sandboxable, but the flow for approval, promoition is different - I have to go to my changes/approvals menu and do promotion there.
After that it start showing on site what was added as translations in admin
That's for enterprise version

Looks like issue is reported for community, need to be investigated

**Comment by oleksiimiroshnyk** [comment]
It's working for enterprise because of advanced cms module.
There is a code in AdvancedCMSAdminAbstractControllerExtensionHandler
```java
        if (form.getCeilingEntityClassname().equals(PageTemplate.class.getName())) {
            form.setTranslationCeilingEntity(Page.class.getName());
            form.setTranslationId(parentEntityId);
        }
```
Not sure why it wasn't done in AdminPageController
@phillipuniverse what do you think if I make same override in AdminPageController ? not sure if why it wasn't done originally and was done in advanced-cms

**Comment by phillipuniverse** [comment]
@oleksiimiroshnyk not sure why that wasn't done in the OOB community, good question and good catch. Likely that distinction was important once upon a time but as code morphed over the years and things converged it didn't make sense anymore and caused a regression in community.

AdvancedCMS also has an override of the community-based `AdminPageController`, not sure exactly what the correct modification is given that context. The way I see it, there are 2 options:

1. Delete the `AdvancedCMSAdminAbstractControllerExtensionHandler` and change the code in `AdminPageController`, and ensure that everything is ok with advanced CMS (basically ensure that `AdminAdvancedPageController` doesn't try to undo what you did)
2. Rename the `AdvancedCMSAdminAbstractControllerExtensionHandler` and move it into community and out of advanced CMS. This should work for all cases and wouldn't impact the fact that the controller is overridden

Take a look at it and let me know what you think we should do.

**Comment by phillipuniverse** [comment]
Moved this out of the 5.2.3-GA milestone since we've already got #1728 there.
