### ISSUE TITLE
uploading media asset

### ISSUE THREAD

**Issue by santoshraju621** [BroadleafCommerce/BroadleafCommerce#1744]
hi i have uploaded a media asset in broadleaf admin this will give the following error

here is the screenshot of error :  

http://i.prntscr.com/0ZhZ3IYaQ4qQ2CTjH7YUVQ.png

here the server log 

http://i.prntscr.com/RpiHm_HyTRGtrKuAR3B8tg.png

please help me to solve the issue

thanks in advane

**Comment by linuxidefix** [comment]
which version of BLC are you using ?

**Comment by santoshraju621** [comment]
what can i do to solve the issue

**Comment by linuxidefix** [comment]
Currently using latest version 5.2.2. Seems to work.
I tried to upload a jpg image. See logs and screenshots below. 
( There is a minor bug in UI because image is not correctly displayed in the asset view. )


![buglog](https://user-images.githubusercontent.com/836182/32799533-5985c47c-c978-11e7-973a-e95a47cee422.png)
![image1](https://user-images.githubusercontent.com/836182/32799534-59a5f0ee-c978-11e7-8616-bcfad090de63.png)
![image2](https://user-images.githubusercontent.com/836182/32799536-59df1aae-c978-11e7-84fe-4d20d5df8d5a.png)

**Comment by santoshraju621** [comment]
hi  i am using 5.2.0-ga is my media asset is not uploading it will gives an error is there any sollution

**Comment by santoshraju621** [comment]
i am using the broadleaf free edition not the enterprise edition

**Comment by cldsnchz** [comment]
I have the same error using the latest DemoSite (and also with ReactStarter).
I guess the error is because the Entity ImageStaticAssetImpl has configured the entity listener AdminAuditableListener. That listener is expecting the method getAuditable in the entity but ImageStaticAssetImpl doesn't have it and because of that the NPE is thrown.

I'm just starting with broadleaf and not sure how to fix the issue.

**Comment by cldsnchz** [comment]
The solution is here: https://stackoverflow.com/questions/46681665/broadleaf-image-upload-failed

Basically is needed to add -javaagent:"path/to/spring-instrument.jar" in the vm arguments. It seems that agent instruments ImageStaticAssetImpl adding the auditable field.

Executing mvn spring-boot:run in the demo site does that automatically, but for running the AdminApplication class directly is needed to add that configuration manually (for example in eclipse).

It would be nice to add this configuration in the eclipse setup page: https://www.broadleafcommerce.com/docs/core/current/getting-started/ide-setup/eclipse-setup like is done in the intellij setup page:https://www.broadleafcommerce.com/docs/core/current/getting-started/ide-setup/intellij-setup)

**Comment by santoshraju621** [comment]
@cldsnchz how can add that java agent to the eclipse please answer me
