### ISSUE TITLE
Override method is never called for controller extends AdminBasicEntityController

### ISSUE THREAD

**Issue by NafanyaVictorovna** [BroadleafCommerce/BroadleafCommerce#2074]
Good day.
I have a question:
I want to extends framework controller by [guide](https://www.broadleafcommerce.com/docs/core/current/broadleaf-concepts/admin/admin-controllers). 
My controller:
```
public class AdminArticleController extends AdminBasicEntityController {

    @Autowired
    private ArticleService articleService;

    @Override
    @RequestMapping(value = "/{id}", method = {RequestMethod.POST}, produces = {"application/json"})
    public String saveEntityJson(HttpServletRequest request, HttpServletResponse response, Model model, @PathVariable Map<String, String> pathVars, @PathVariable("id") String id, @ModelAttribute("entityForm") EntityForm entityForm, BindingResult result, RedirectAttributes ra) throws Exception {
        System.out.println("save method");
        articleService.getCommentsByArticle(Long.decode(id), entityForm.getFields().get("CATEGORY").getFieldType());
        articleService.updateArticleEntity();
        return super.saveEntityJson(request, response, model, pathVars, id, entityForm, result, ra);
    }
}
```
Also I added bean info to AdminServletConfig:
```
    @Bean
    public AdminBasicEntityController blAdminBasicEntityController() {
        return new AdminArticleController();
    }

```
But my method is never used, when I am debugging program, the parent controller always catches the call.
What's wrong? Why it happends?

**Comment by Jerry77oz** [comment]
Hi @NafanyaVictorovna,

This channel is meant for issues/bugs found in the framework. Community support questions can be directed to our Gitter page - https://gitter.im/BroadleafCommerce/BroadleafCommerce

Having said that, for what you are doing, take a look at the `AdminProductController`, this would be an example of how the  `AdminBasicEntityController`. From the documentation you linked make sure you define `getSectionKey()`:

> If you are going to be extending `AdminBasicEntityController` directly because Broadleaf does not already provide a section specific controller for your entity, you can use `AdminProductController` as a model for your desired behavior and disregard the rest of this document. Please do note that the `getSectionKey()` method as seen in `AdminProductController` is required and must be copied over to your controller.

Also, you are overriding an existing method that already has a defined `@RequestMapping`. In these cases you only want to override the method otherwise you will get an error from Spring complaining about ambiguous request mappings.

**Comment by NafanyaVictorovna** [comment]
I am sorry, I didn't find the gitter community.
Thank you for link and advice, it helped.
