### ISSUE TITLE
mvn install fails due to inability to fetch broadleaf-common-presentation-1.1.0-GA.jar

### ISSUE THREAD

**Issue by maksymbaziuk** [BroadleafCommerce/BroadleafCommerce#2205]
I tried to install locally broadleaf-6.0.6.2-GA but getting "[ERROR] Failed to execute goal on project broadleaf-common: Could not resolve dependencies for project org.broadleafcommerce:broadleaf-common:jar:6.0.6.2-GA: Could not transfer artifact org.broadleafcommerce:broadleaf-common-presentation:jar:1.1.0-GA from/to releases (http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/): GET request of: org/broadleafcommerce/broadleaf-common-presentation/1.1.0-GA/broadleaf-common-presentation-1.1.0-GA.jar from releases failed: Premature end of Content-Length delimited message body (expected: 27,736; received: 965) -> [Help 1]" (the same for broadleaf-6.0.6-GA.zip from https://www.broadleafcommerce.com/docs/core/current/getting-started/running-locally).
Trying download this JAR manually from http://nexus.broadleafcommerce.org/nexus/content/groups/community-releases/org/broadleafcommerce/broadleaf-common-presentation/1.1.0-GA/ resulting in the same failure (receiving around 3.8Kb and fails). It looks like some limitations on Nexus (tried to download other things from there results in the same error).
Could you please check?

**Comment by danielcolgrove** [comment]
@maksymbaziuk The nexus server looks okay and I've double checked our monitoring system and we've received no downtime alerts.  I also verified our builds are working and I did a local test with a fresh build as well as a fresh install of the demo site (getting started link).  Just wanted to check the key places that calls from Nexus would originate.

It does sounds like a connection issue since you mentioned trying to download manually also failed.  Are you possibly routing through a proxy server or any route that could add latency?

**Comment by maksymbaziuk** [comment]
Could be, tried to change the network to mobile internet - the same. Will check on other PC...

**Comment by linuxidefix** [comment]
@maksymbaziuk Remove the corrupted file from your local maven repository and run maven install. You may had a problem when downloading the jar file the 1st time.

`~/.m2/repository/org/broadleafcommerce/broadleaf-common-presentation`

**Comment by maksymbaziuk** [comment]
Issue solved. It was the partial occupation of ports for FTP by a VPN tool.
Thanks for the quick response and sorry  :)
