### ISSUE TITLE
Add default getters and setters to the REST API wrapper classes

### ISSUE THREAD

**Issue by ktisdell** [BroadleafCommerce/BroadleafCommerce#651]
We found on client work recently that, even though the wrap and unwrap methods are generally good enough in most cases.  It would be nice to have getters and setters on the wrapper classes.

**Comment by gdiazblc** [comment]
In the same line of thinking:
The unwrap methods, when available, not always are suitable to be invoked to help with a RESTful operation, because they often assume more presence in the repository than what is desirable for a simple, CRUD-style POST, for example.
Moreover, slightly different versions of the unwrap methods should apply to different REST methods, (check SubscriptionWrapper as an example).

**Comment by phillipuniverse** [comment]
This is resolved in 4.0.
