### ISSUE TITLE
Refactor BaseActivity and set the default automaticallyRegisterRollbackHandler to "false"

### ISSUE THREAD

**Issue by elbertbautista** [BroadleafCommerce/BroadleafCommerce#93]
Consider Refactoring BaseActivity and set the default automaticallyRegisterRollbackHandler to "false" because in most cases if you define an activity with a Rollback Handler. The activity itself needs to programmatically register itself with the Activity Manager instead of having the SequenceProcessor register it. Right now as it is set to "true", the activities that do register a rollback have to manually set it and produce some boiler plate code. See: org.broadleafcommerce.inventory.service.workflow.DecrementInventoryActivity and org.broadleafcommerce.core.payment.service.workflow.PaymentActivity

``` java
if (getRollbackHandler() != null && !getAutomaticallyRegisterRollbackHandler()) {
  ...
}
```

In the cases of the existing activities, the Rollback Handlers are null anyways so the logic in the SequenceProcessor should still work if you set automaticallyRegisterRollbackHandler to "false"

``` java
if (activity.getRollbackHandler() != null && activity.getAutomaticallyRegisterRollbackHandler()) { 
  ActivityStateManagerImpl.getStateManager().registerState(activity, context, activity.getRollbackRegion(), activity.getRollbackHandler(), activity.getStateConfiguration());
}
```

**Comment by daniellavoie** [comment]
Hi there guys, I came across this change because I actually encountering a problem with the **ValidateAndConfirmPaymentActivity**. I can see that I have a registered rollback handler but the famous flag **automaticallyRegisterRollbackHandler** is set to **false**. As a result my rollback handler is not being registered. 

```
if (activity.getRollbackHandler() != null && activity.getAutomaticallyRegisterRollbackHandler()) {
    ActivityStateManagerImpl.getStateManager().registerState(activity, context, activity.getRollbackRegion(), activity.getRollbackHandler(), activity.getStateConfiguration());
}
```

I don't get the logic behind this behavior. Could you guys light me up about why the **ValidateAndConfirmPaymentActivity** does not register itself ?

I can see the proper behavior with the following activities : 
* CommitTaxActivity
* CompleteOrderActivity
* DecrementInventoryActivity

**Comment by daniellavoie** [comment]
Ohhhhhh !

Ok I got it all wrong :)

I've seen now that is does register his state by itself inside the **execute()** method. Sorry for bothering !

```
ActivityStateManagerImpl.getStateManager().registerState(this, context, getRollbackHandler(), rollbackState);
```
